steps:

# Decrypt the file containing the SSH key for GitHub authentication
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=conf/id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=cloudbuild-secrets
  - --key=cloudbuild-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
     IdentityFile /root/.ssh/id_rsa
    EOF
    cp conf/known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# # test git auth configuration
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     cat /root/.ssh/id_rsa
#     ssh -vT git@github.com
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# clone the git repository. We will push some changes to it.
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - ${_GIT_REPO}
  - tmp-requests 
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# checkout the branch this request came from
- name: 'gcr.io/cloud-builders/git'
  args:
  - -C
  - /workspace/tmp-requests
  - checkout
  - $BRANCH_NAME
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# initialize terraform using the updated terraform folder.
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - init
  - /workspace/tmp-requests/terraform

# run a terraform plan to check what changes will be made.
- name: gcr.io/$PROJECT_ID/terraform
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    terraform plan -no-color -input=false \
    -var-file=/workspace/tmp-requests/terraform/params.tfvars \
    -out=/workspace/tmp-requests/tf_plan.bin \
    /workspace/tmp-requests/terraform > /workspace/terraform_output.txt

# encode the plan to protect any secrets that may have been included
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - encrypt
  - --plaintext-file=/workspace/tmp-requests/tf_plan.bin
  - --ciphertext-file=/workspace/tmp-requests/tf_plan.enc
  - --location=global
  - --keyring=cloudbuild-secrets
  - --key=cloudbuild-key

# add the terraform config changes for commit.
- name: 'gcr.io/cloud-builders/git'
  args:
  - -C
  - /workspace/tmp-requests
  - add
  - tf_plan.enc
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set the user email and name for the commit
- name: 'gcr.io/cloud-builders/git'
  args:
  - config
  - --global
  - user.email
  - "${_GIT_MAIL}"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  args:
  - config
  - --global
  - user.name
  - "${_GIT_USER}"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# commit the changes, adding the output from the terraform plan as commit comment.
- name: 'gcr.io/cloud-builders/git'
  args:
  - -C
  - /workspace/tmp-requests
  - commit
  - --author="${_GIT_USER} <${_GIT_MAIL}>"
  - --file=/workspace/terraform_output.txt
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# push the changes
- name: 'gcr.io/cloud-builders/git'
  args:
  - -C
  - /workspace/tmp-requests
  - push
  - -u
  - origin
  - $BRANCH_NAME
  volumes:
  - name: 'ssh'
    path: /root/.ssh
